### ISSUE TITLE
Java Error

### ISSUE THREAD

**Issue by eayan** [bnosac/RDRPOSTagger#3]
Hi,

while installing RDRPOSTagger, it comes up with the error. Can someone help me solve the problem?
![image](https://user-images.githubusercontent.com/5304822/42332463-50b54360-8078-11e8-9679-964234774595.png)

Best...

**Comment by jwijffels** [comment]
Install Java.

**Comment by eayan** [comment]
Hi,
I have actually installed it even though there occured some missing libraries. But it did not work unfortunately.
Best..

Android’de Yahoo Postadan gönderildi 
 
  21:14’’5e’ 5 Tem 2018 Per tarihinde, jwijffels<notifications@github.com> şunu yazdı:   
Install j

**Comment by jwijffels** [comment]
Please ask the question on stackoverflow. Installing java is unrelated to this R package. Make sure you install the Java JVM

**Comment by eayan** [comment]
Hi,
you can find the errors in the attached files, the first one is from Windows machine the other one is from Linux (mint). I have tried to install java jvm but there is not a package in R for that. If you provide me with the link of the issue on Stackoverflow, I can also share it there.
 

With my best regards...
==========
Erdal Ayan, M.A.-M.Sc.
Department of Mathematics & InformaticsPhilipps Universität Marburg==========
Academic AssistantDigital History & ITHerder Institut-MarburgGermany  

    On Friday, July 6, 2018, 9:22:04 AM GMT+2, jwijffels <notifications@github.com> wrote:  
 
 
Please ask the question on stackoverflow. Installing java is unrelated to this R package. Make sure you install the Java JVM

**Comment by jwijffels** [comment]
Java JVM is not an  R package. Please go to stackoverflow with your question or type in java jvm and install the java software. Your error is unrelated to the RDRPOSTagger R package.
