### ISSUE TITLE
installation failed because of Java?

### ISSUE THREAD

**Issue by lbocken** [bnosac/RDRPOSTagger#5]
My installation failed. Notice that the command 'library(rJava)' works fine and the R package 'wordnet' importing rJava works fine... So I don't understand exactly the problem because java doesn't seem to be a cause of problems with other packages...

`devtools::install_github("bnosac/RDRPOSTagger")
Downloading GitHub repo bnosac/RDRPOSTagger@master
√  checking for file 'C:\Users\Ludovic\AppData\Local\Temp\RtmpGqPYPs\remotes4de47ddc3d23\bnosac-RDRPOSTagger-af51e38/DESCRIPTION' ... 
-  preparing 'RDRPOSTagger': (5.8s)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (3.1s)
-  checking for empty or unneeded directories
-  building 'RDRPOSTagger_1.1.tar.gz'
   
Installing package into ‘C:/Users/Ludovic/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'RDRPOSTagger' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'RDRPOSTagger'
    finding HTML links ... fini
    rdr_add_space_around_punctuations       html  
    rdr_available_models                    html  
    rdr_model                               html  
    rdr_pos                                 html  
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'rJava':
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: fun(libname, pkgname)
  error: No CurrentVersion entry in Software/JavaSoft registry! Try re-installing Java and make sure R and Java have matching architectures.
Error : package 'rJava' could not be loaded
Erreur : le chargement a échoué
Exécution arrêtée
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/Ludovic/Documents/R/win-library/3.6/RDRPOSTagger'
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/Ludovic/AppData/Local/Temp/RtmpGqPYPs/file4de46a333221/RDRPOSTagger_1.1.tar.gz’ had non-zero exit status`

**Comment by jwijffels** [comment]
It's a java problem, not a problem of this R package. Please look online on how you install java, make sure your R version 64/32 bit and your java version which you installed is similarly 64/32 bit. And if you did not install java in either 64 or 32 bit, install only the corresponding 64/32 bit of this r package e.g. as in devtools::install_github("bnosac/RDRPOSTagger", INSTALL_opts = "--no-multiarch")
Or just use the udpipe R package, it provides the same as this R package, better performance, better accuracy and less package dependencies or external software installation problems. https://github.com/bnosac/udpipe

**Comment by lbocken** [comment]
With no other java reinstallation, this works:
`devtools::install_github("bnosac/RDRPOSTagger", INSTALL_opts = "--no-multiarch")
`
Thank you very much !

**Comment by Allan-pixe** [comment]
Hi Jan, 
I tried to install the package, but I keep getting this: 
Error: Failed to install 'RDRPOSTagger' from GitHub:
 (converted from warning) installation of package ‘C:/Users/31630/AppData/Local/Temp/Rtmp6pfImc/file1220783e5a99/RDRPOSTagger_1.1.tar.gz’ had non-zero exit status

Can you kindly help? 

Allan

**Comment by Allan-pixe** [comment]
Indeed, this worked for me as well : devtools::install_github("bnosac/RDRPOSTagger", INSTALL_opts = "--no-multiarch")

(I had to first uninstall java ) 

Thank you for the comments!
